/**
 * What each step-up operation asks the user to authorise, in words.
 *
 * The modal used to print the raw operation id ("Operation: create-ca"), which told a support
 * engineer what happened and told the user nothing. Every value in StepUpOps has a sentence
 * here; an id with no entry falls back to the id itself, so a new operation is never hidden.
 */
const TEXT: Record<string, string> = {
    'switch-badge': 'Switch the badge this session wears',
    'manage-kerberos-realm': 'Change a Kerberos realm binding or its keys',
    'manage-tenant-hostname': 'Add, remove or reissue a hostname a tenant is reached by',
    'revoke-cert': 'Revoke a certificate',
    'hold-cert': 'Place a certificate on hold',
    'unhold-cert': 'Lift the hold on a certificate',
    'revoke-self-cert': 'Revoke one of your own certificates',
    'reissue-cert': 'Reissue a certificate with a new key',
    'export-cert': 'Export a certificate and its private key',
    'update-cert-acl': 'Change who may access a certificate',
    'create-user': 'Create a user account',
    'update-user': 'Change a user account',
    'delete-user': 'Delete a user account',
    'add-group-member': 'Add a member to a group',
    'remove-group-member': 'Remove a member from a group',
    'update-user-groups': 'Change the groups a user belongs to',
    'create-group': 'Create a group',
    'delete-group': 'Delete a group',
    'update-group': 'Change a group',
    'grant-user-capability': 'Grant a capability directly to a user',
    'revoke-user-capability': 'Revoke a capability granted directly to a user',
    'create-role': 'Create a role',
    'update-role': 'Change a role',
    'delete-role': 'Delete a role',
    'assign-role': 'Assign a role',
    'unassign-role': 'Remove a role assignment',
    'reset-password': "Reset another user's password",
    'reset-mfa': "Reset another user's multi-factor authentication",
    'change-password': 'Change your password',
    'change-email': 'Change your email address',
    'create-backup': 'Create a backup',
    'restore-backup': 'Restore from a backup',
    'set-backup-password': 'Set the backup encryption password',
    'change-backup-encryption-mode': 'Change how backups are encrypted',
    'create-ca': 'Create a certificate authority',
    'update-ca': 'Change a certificate authority',
    'revoke-ca': 'Revoke a certificate authority',
    'reissue-infrastructure-certs': "Reissue a CA's OCSP or CMP signing certificates",
    'update-signing-profile': 'Change a signing profile',
    'delete-signing-profile': 'Delete a signing profile',
    'update-cert-profile': 'Change a certificate profile',
    'delete-cert-profile': 'Delete a certificate profile',
    'update-request-profile': 'Change a request profile',
    'delete-request-profile': 'Delete a request profile',
    'create-whitelist': 'Create a network allow-list rule',
    'update-whitelist': 'Change a network allow-list rule',
    'delete-whitelist': 'Delete a network allow-list rule',
    'policy-sync': 'Synchronise policy from the directory',
    'policy-import': 'Import policy',
    'update-protocol-config': "Change a CA's enrollment protocol settings",
    'update-config': 'Change system settings',
    'restart': 'Restart the service',
    'create-ssh-ca': 'Create an SSH certificate authority key',
    'disable-ssh-ca': 'Disable an SSH certificate authority key',
    'initiate-ceremony': 'Start a ceremony',
    'approve-ceremony': 'Approve a ceremony',
    'reject-ceremony': 'Reject a ceremony',
    'cancel-ceremony': 'Cancel a ceremony',
    'execute-ceremony': 'Execute an approved ceremony',
    'disable-ceremony-requirement': 'Turn off the ceremony requirement',
    'update-scheduler-job': 'Change a scheduled job',
    'run-scheduler-job': 'Run a scheduled job now',
    'update-scheduler-schedule': 'Change a schedule',
    'delete-scheduler-schedule': 'Delete a schedule',
    'run-scheduler-schedule': 'Run a schedule now',
    'update-scheduler-config': 'Change the scheduler settings',
    'create-crl-schedule': 'Create a CRL schedule',
    'update-crl-schedule': 'Change a CRL schedule',
    'delete-crl-schedule': 'Delete a CRL schedule',
    'toggle-crl-schedule': 'Enable or disable a CRL schedule',
    'manage-oid-catalog': 'Change the OID catalogue',
    'create-ldap-publisher': 'Create an LDAP publisher',
    'update-ldap-publisher': 'Change an LDAP publisher',
    'delete-ldap-publisher': 'Delete an LDAP publisher',
    'bulk-crl-schedule': 'Change several CRL schedules at once',
    'bulk-ldap-publisher': 'Change several LDAP publishers at once',
    'create-ct-log': 'Add a Certificate Transparency log',
    'update-ct-log': 'Change a Certificate Transparency log',
    'delete-ct-log': 'Remove a Certificate Transparency log',
    'create-certificate-template': 'Create a certificate template',
    'update-certificate-template': 'Change a certificate template',
    'delete-certificate-template': 'Delete a certificate template',
    'update-ca-service-url': "Change a CA's published service URLs",
    'delete-ca-service-url': "Remove a CA's published service URLs",
    'update-feature-flag': 'Change a feature flag',
    'delete-eab-key': 'Delete an ACME external account binding key',
    'create-ssh-profile': 'Create an SSH profile',
    'update-ssh-profile': 'Change an SSH profile',
    'delete-ssh-profile': 'Delete an SSH profile',
    'totp-setup': 'Set up an authenticator app',
    'totp-verify-setup': 'Confirm the authenticator app setup',
    'totp-remove': 'Remove the authenticator app',
    'webauthn-register': 'Register a security key',
    'webauthn-delete': 'Remove a security key',
    'mtls-enroll': 'Enroll a client certificate for sign-in',
    'mtls-delete': 'Remove a client certificate used for sign-in',
    'enable-tenant': 'Enable a tenant',
    'disable-tenant': 'Disable a tenant',
    'update-tenant-settings': "Change a tenant's settings",
};

/** The sentence for an operation id, or the id itself when none is known. */
export function describeStepUpOperation(operation: string): string {
    return TEXT[operation] ?? operation;
}
